### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jmmarko** [lkrsnik/simple_accentuation#1]
I am trying to set up your solution using Docker, but I get the following error:

`Using Theano backend.`
`WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.`
`ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check`
`ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, 36, 23, 1), kshp=(115, 36, 3, 1), filter_dilation=(1, 1)}(InplaceDimShuffle{0,2,1,x}.0, InplaceDimShuffle{2,1,0,x}.0)`
`ERROR (theano.gof.opt): TRACEBACK:`
`ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python3.5/dist-packages/theano/tensor/nnet/opt.py", line 615, in local_abstractconv_check
    node.op.__class__.__name__)
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?`

`Traceback (most recent call last):
  File "accentuate_connected_text.py", line 40, in <module>
    'models/syllabled_letters_place_20_test_epoch.h5')
  File "/app/prepare_data.py", line 1072, in load_location_models
    letter_location_model = load_model(letters_path, custom_objects={'actual_accuracy': actual_accuracy})
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 268, in load_model
    model._make_train_function()
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1007, in _make_train_function
    **self._function_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/theano_backend.py", line 1104, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/theano_backend.py", line 1090, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 1794, in orig_function
    output_keys=output_keys).create(
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 1474, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 2095, in apply
    nb += self.process_node(fgraph, node)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 1987, in process_node
    lopt, node)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 1881, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 1867, in warn
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python3.5/dist-packages/theano/tensor/nnet/opt.py", line 615, in local_abstractconv_check
    node.op.__class__.__name__)
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?`

Do you maybe have any idea what I am missing? What Python version did you use?

My Dockerfile:

`FROM ubuntu:18.04`

`RUN apt-get update`
`RUN apt-get install -y software-properties-common`
`RUN add-apt-repository ppa:deadsnakes/ppa`
`RUN apt-get update`
`RUN apt-get install -y python3.5-dev`
`RUN apt-get install -y git`
`RUN apt-get install -y curl`
`RUN curl https://bootstrap.pypa.io/ez_setup.py -o - | python3.5`
`RUN easy_install pip`

`COPY . /app`
`WORKDIR /app`
`RUN pip install -r requirements.txt`

`RUN git clone https://github.com/clarinsi/reldi-tagger`

The command to start the docker container and the command that I run inside docker container:

`docker run -it --gpus all simple_accentuation`

`KERAS_BACKEND=theano python3.5 accentuate_connected_text.py 'test_data/original_connected_text' 'test_data/accented_connected_text' 'reldi-tagger'`

**Comment by lkrsnik** [comment]
I am guessing your problem has something to do with drivers required by Theano.

I updated this repo with working [dockerfile](https://github.com/lkrsnik/simple_accentuation/blob/master/Dockerfile.py3-th-cpu) (I also had to fix some other issues in code so make sure to pull latest commit). In it you will see that I used python3.5 and also python2.7 for running reldi-tagger.

You can run it with:
`docker run -it simple_accentuation`
`theano python3.5 accentuate_connected_text.py 'test_data/original_connected_text' 'test_data/accented_connected_text' 'reldi-tagger'`

This dockerfile unfortunately supports only CPU processing. If you would like to run it with GPUs I suggest [these](https://github.com/gw0/docker-keras) docker templates.

I hope this helps.
